---
- name: Perform a Git push to remote server
  expect:
    command: "git push {{ destination_remote }} {{ destination_branch }}"
    chdir: "{{ local_repo_path }}"
    responses:
     (?i)yes/no: "yes"
     (?i)password: "{{ ansible_ssh_pass }}"
  delegate_to: localhost


- name: check git diff on remote server to be sure no one changed any file there
  command:
    cmd: "git diff HEAD --stat"
    chdir: "{{ remote_repo_path }}"
  register: gitdiff

- name: show error if there is an issue in GIT DIFF
  debug:
    msg: "!!!!!!please check {{ remote_repo_path }} seems files are changed!!!!!"
  when: gitdiff.stdout != ""

- name: Perform a Git pull from Repository in Remote server
  git:
     repo: "{{ remote_repo_url }}"
     dest: "{{ remote_repo_path }}"
     update: yes
     remote: "{{ remote_srv_remote }}"
     version: "{{ remote_srv_branch }}"
  register: gitpull_reg


- name: show updated files
  command:
    cmd: "git show {{ gitpull_reg.after }}"
    chdir: "{{ remote_repo_path }}"
  when: gitpull_reg.after != gitpull_reg.before
  register: git_new_update

- name: show new changes on git
  debug:
    msg: "{{ git_new_update.stdout_lines }}"
  when: gitpull_reg.after != gitpull_reg.before

- name: Creating a file with content
  copy:
    content: "{{ git_new_update.stdout }}"
    dest: "{{ jenkins_pipeline_path }}/git_changes.txt"
  delegate_to: localhost 
  when: gitpull_reg.after != gitpull_reg.before
