---
# tasks file for gitlab_pull_push
- name: Ensure the Git repository is cloned from GitLab
  git:
    repo: "{{ gitlab_repo_url }}"
    dest: "{{ local_repo_path }}"
    remote: "{{ source_remote }}"
    clone: yes

- name: Perform a Git pull from Repository in GitLab
  git:
    repo: "{{ gitlab_repo_url }}"
    dest: "{{ local_repo_path }}"
    update: yes
    force: yes
    remote: "{{ source_remote }}"
    version: "{{ source_branch }}"

- name: list remopts
  command:
    cmd: "git remote -v"
    chdir: "{{ local_repo_path }}"
  register: cur_remote_reg


- name: add remote to local repo
  command:
    cmd: "git  remote add {{ item }}"
    chdir: "{{ local_repo_path }}"
  with_items:
    - "{{ local_remote_vars }}"
  ignore_errors: True

