---
- name: Pull from GitLab Repository  and Push to Another Server Repository
  hosts: all 
  gather_facts: no
    
  roles:
     #if you want to run manual comment out this line
     #- {role: gitlab_clone , delegate_to: localhost}
     - {role: git_add_remotes , delegate_to: localhost}
     - role: push_to_remote_server 
  

