---
# tasks file for reload docker-compose

- name: stop docker-compose
  shell:
    cmd: "/bin/docker-compose down"
    chdir: "{{ docker_compose_file_path }}"
  register: down_reg

- debug:
    var: down_reg
