---
# tasks file for reload docker-compose

- name: stop docker-compose
  shell:
    cmd: "docker-compose down"
    chdir: "{{ docker_compose_file_path }}"
  register: down_reg

- debug:
    var: down_reg


- name: load docker-compose with new images
    cmd: "docker-compose up -d"
    chdir: "{{ docker_compose_file_path }}"
  register: up_reg

- debug:
    var: up_reg
