---
# tasks file for reload docker-compose

- name: stop docker-compose
  shell:
    cmd: "/bin/docker-compose down"
    chdir: "{{ docker_compose_file_path }}"
  register: down_reg

- name: print stop result
  debug:
    var: down_reg

- name: start docker-compose
  shell:
    cmd: "/bin/docker-compose up -d "
    chdir: "{{ docker_compose_file_path }}"
  register: up_reg

- name: print start result
  debug:
    var: up_reg
