---
- name: build docker image file and reload application with new image
  hosts: all 
  gather_facts: no
  collections:
    - community.docker

  roles:
     - {role: build_deploy_image , delegate_to: localhost}

