---
# tasks file for build_image_role

- name: Build an image
  community.docker.docker_image:
    build:
      path: "{{ DOCKER_FILE_PATH }}"
      dockerfile: Dockerfile
    name: "{{ DOCKER_IMAGE_NAME }}"
    tag: "{{ DOCKER_IMAGE_TAG }}"
    force_tag: true
    source: build
