---
- name: Copy file with owner and permissions
  copy:
    src: "{{ jenkins_pipeline_path }}/file1.py"
    dest: /tmp/file1.py


- name: Run command  on the application installed in django_dir
  django_manage:
    command: shell -c "exec(open('/tmp/file1.py').read())"
    app_path: "{{ django_dir }}"
    virtualenv: "{{ virtenv_var }}"
    pythonpath: "{{ pythonpath_var }}"
  register:  django_shell_register


- name: Creating a file with content
  copy:
    content: "{{ django_shell_register.out }}"
    dest: "{{ jenkins_pipeline_path }}/result.log"
  delegate_to: localhost


- name: remove files from server
  file:
    path: "/tmp/file1.py"
    state: absent
