---
- name: Copy file with owner and permissions
  copy:
    src: "{{ jenkins_pipeline_path }}/file1.py"
    dest: /tmp/file1.py

- name: Copy datafile
  copy:
    src: "{{ jenkins_pipeline_path }}/{{ datafile }}"
    dest: "{{ django_dir }}/{{ datafile }}"
  when: datafile!=""  


- name: Run command  on the application installed in django_dir
  django_manage:
    command: shell -c "exec(open('/tmp/file1.py').read())"
    app_path: "{{ django_dir }}"
    virtualenv: "{{ virtenv_var }}"
    pythonpath: "{{ pythonpath_var }}"
  register:  django_shell_register


- name: Creating a file with content
  copy:
    content: "{{ django_shell_register.out }}"
    dest: "{{ jenkins_pipeline_path }}/result.log"
  delegate_to: localhost


- name: remove files from server
  file:
    path: "/tmp/file1.py"
    state: absent

- name: Copy datafile
  file:
    path: "{{ jenkins_pipeline_path }}/{{ datafile }}"
    state: absent
  when: datafile!="

  # - name: Find lines with "w" as a word in a file
  #   shell:
  #     cmd: "cat /tmp/1 |grep -iE 'with\\s+open\\(' |grep -iE '\\bw\\b'| cut -d ',' -f 1 |cut -d '(' -f 2 | sed  \"s/'//g\" | sed  's/\"//g'  "
  #   register: found_lines
