---
- set_fact:
        my_string: "[import os,import sys]"
- set_fact:
    my_list: "{{ my_string | regex_replace('\\[|\\]', '')  | map('split', ',')|flatten }}"
        
- debug:
    var: my_list


- name: Run command  on the application installed in django_dir
  django_manage:
    command: shell -c '{{ item }}'
    app_path: "{{ django_dir }}"
    virtualenv: "{{ virtenv_var }}"
    pythonpath: "{{ pythonpath_var }}"
  with_items:   "{{ my_list }}"
  register:  django_shell_register


- debug:
    var: django_shell_register
