---
- set_fact:
        my_string: "[import os,import sys]"
- set_fact:
    my_list: "{{ my_string.split(',') | regex_replace('\\[|\\]', '')|flatten }}"
        
- debug:
    var: my_list


- name: Run command  on the application installed in django_dir
  django_manage:
    command: shell -c '{{ item }}'
    app_path: "{{ django_dir }}"
    virtualenv: "{{ virtenv_var }}"
    pythonpath: "{{ pythonpath_var }}"
  with_items:   "{{ django_shell_commands }}"
  register:  django_shell_register


- debug:
    var: django_shell_register
