---
- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: "{{ jenkins_pipeline_path }}/file1.py"
    dest: /tmp/file1.py


- name: Run command  on the application installed in django_dir
  django_manage:
    command: shell -c "exec(open('/tmp/file1.py').read())"
    app_path: "{{ django_dir }}"
    virtualenv: "{{ virtenv_var }}"
    pythonpath: "{{ pythonpath_var }}"
  register:  django_shell_register


- debug:
    var: django_shell_register

