---
- name: Perform a Git pull from Repository in GitLab
  expect:
    command: "git pull {{ remote_srv_remote }} {{ remote_srv_branch }}"
    chdir: "/home/appuser/python_test"
    
    responses:
     (?i)Username for.*: "{{ GIT_USERNAME_VAL }}"
     (?i)Password for.*: "{{ GIT_PASSWORD_VAL }}"
  register: gitdiff   
  

- name: print git diff
  debug:
    var: gitdiff

- name: Creating a file with content
  copy:
    content: "{{ gitdiff.stdout_lines | join('<br>') }}"
    dest: "/tmp/git_changes.txt"
  delegate_to: localhost 


     



