---
- name: Perform a Git pull from Repository in GitLab
  expect:
    command: "git pull {{ remote_srv_remote }} {{ remote_srv_branch }}"
    chdir: "/home/appuser/python_test"
    responses:
     (?i)Username for.*: "{{ GIT_USERNAME_VAL }}"
     (?i)Password for.*: "{{ GIT_PASSWORD_VAL }}"



